source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GSTestKit_Example', :exclusive => true do
  pod 'GSTestKit', :path => '../'
end

target 'GSTestKit_Tests', :exclusive => true do
  pod 'GSTestKit', :path => '../'

  
end
